// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice.Data;

#nullable disable

namespace Practice.Data.Migrations
{
    [DbContext(typeof(PracticeDbContext))]
    partial class PracticeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Practice.Data.Models.Drill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RowCreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RowCreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("RowModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RowModifiedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Drills");
                });

            modelBuilder.Entity("Practice.Data.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PracticeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RowCreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RowCreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("RowModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RowModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Practice.Data.Models.Session_Drill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrillId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrillId2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PerformanceRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RowCreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RowCreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("RowModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RowModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId2")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DrillId");

                    b.HasIndex("DrillId1");

                    b.HasIndex("DrillId2");

                    b.HasIndex("SessionId1");

                    b.HasIndex("SessionId2");

                    b.HasIndex("SessionId", "DrillId")
                        .IsUnique();

                    b.ToTable("SessionDrills");
                });

            modelBuilder.Entity("Practice.Data.Models.Session_Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RowCreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RowCreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("RowModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RowModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId2")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId1");

                    b.HasIndex("SessionId2");

                    b.HasIndex("SongId");

                    b.HasIndex("SongId1");

                    b.HasIndex("SongId2");

                    b.HasIndex("SessionId", "SongId")
                        .IsUnique();

                    b.ToTable("SessionSongs");
                });

            modelBuilder.Entity("Practice.Data.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RowCreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RowCreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("RowModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RowModifiedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Practice.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RowCreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RowCreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("RowModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RowModifiedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Practice.Data.Models.Session", b =>
                {
                    b.HasOne("Practice.Data.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Practice.Data.Models.Session_Drill", b =>
                {
                    b.HasOne("Practice.Data.Models.Drill", null)
                        .WithMany()
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Practice.Data.Models.Drill", "Drill")
                        .WithMany()
                        .HasForeignKey("DrillId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practice.Data.Models.Drill", null)
                        .WithMany()
                        .HasForeignKey("DrillId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practice.Data.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Practice.Data.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practice.Data.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drill");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Practice.Data.Models.Session_Song", b =>
                {
                    b.HasOne("Practice.Data.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Practice.Data.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practice.Data.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practice.Data.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Practice.Data.Models.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practice.Data.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("SongId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Practice.Data.Models.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
